name: photoportfolio
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  fonts:
    - family: Italiana
      fonts:
        - asset: assets/fonts/Italiana-Regular.ttf
  uses-material-design: true
  assets:
    - assets/res/beforeAfter/
    - assets/res/work/
    - assets/res/work/names.json
    - assets/res/about.jpg
  